USE db_hunter_facture_juanEscalante;
DROP DATABASE db_hunter_facture_juanEscalante;
CREATE DATABASE db_hunter_facture_juanEscalante;
CREATE TABLE PRODUCT(
 ID INTEGER(11) AUTO_INCREMENT PRIMARY KEY COMMENT 'ID DE PRODUCTO',
 NAME CHAR(50) NOT NULL COMMENT 'NOMBRE DE PRODUCTO',
 AMOUNT INT(3) DEFAULT 1 COMMENT 'CANTIDAD',
 VALUE INT(10) NOT NULL COMMENT 'PRECIO UNITARIO'
);
CREATE TABLE CUSTOMER(
 ID INTEGER(11) AUTO_INCREMENT PRIMARY KEY COMMENT 'ID DE CLIENTE',
 NAME CHAR(50) NOT NULL COMMENT 'NOMBRE DEL CLIENTE',
 EMAIL VARCHAR(77)  COMMENT 'CORREO ELECTRONICO',
 PHONE INT(10) NOT NULL COMMENT 'TELEFONO',
 ADDRESS VARCHAR(50) NOT NULL UNIQUE COMMENT 'DIRECCION'
);

CREATE TABLE SELLER(
 ID INTEGER(11) AUTO_INCREMENT PRIMARY KEY COMMENT 'ID DEL VENDEDOR',
 NAME CHAR(50) NOT NULL COMMENT 'NOMBRE DEL VENDEDOR'
);
CREATE TABLE BILL(
 ID INTEGER(11) AUTO_INCREMENT PRIMARY KEY COMMENT 'ID DE FACTURA',
 _DATE DATETIME NOT NULL DEFAULT NOW() UNIQUE COMMENT 'FECHA DE FACTURACION',
 ID_SELLER INT(11) NOT NULL,
 FOREIGN KEY(ID_SELLER) REFERENCES SELLER(ID),
 ID_CUSTOMER INT(11) NOT NULL,
 FOREIGN KEY(ID_CUSTOMER) REFERENCES CUSTOMER(ID),
 ID_PRODUCT INT(11) NOT NULL,
 FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID)
);